### PR TITLE
bump versions and images

### LINKED ISSUE #91: [dependency-track] Upgrade to 4.3
**Is your feature request related to a problem? Please describe.**
Upgrade to latest 4.3.x release in order to get new features, specifically the OIDC changes which are favourable, as well as supposedly fixing the infamous postgresql infinite-loop bug.

Also, please upgrade the postgres child chart to latest compatible version.

release notes: https://docs.dependencytrack.org/changelog/

### PR DESCRIPTION
**Pull request by Otterian**
Fixes #91

### CODE REVIEW

**Comment by Otterian** [comment]
Implements https://github.com/evryfs/helm-charts/issues/91

**Comment by Otterian** [comment]
What is https://github.com/evryfs/helm-charts/blob/f95c57ce18cf5ced2923c15d733e1a59bdb51622/charts/dependency-track/Chart.yaml#L26-L28 @davidkarlsen ?

**Comment by Otterian** [comment]
In any case, do we also want to bump the common charts, or leave it as it is?

**Comment by davidkarlsen** [comment]
> In any case, do we also want to bump the common charts, or leave it as it is?

thats the library helper-chart from bitnami, which can be used as "functions", so yes, let's upgrade that too.

**Review by davidkarlsen — CHANGES_REQUESTED** [review]
we need the lockfile, update the requirements in Chart.yaml, then run `helm dependency update` to generate it and check it in

**Comment by Otterian** [comment]
> > In any case, do we also want to bump the common charts, or leave it as it is?
> 
> thats the library helper-chart from bitnami, which can be used as "functions", so yes, let's upgrade that too.

To latest? 1.8.0?

**Review by davidkarlsen — APPROVED** [review]
lgtm!
thanks!

**Pull request merged**
