### PR TITLE
Fix/dependency track

### PR DESCRIPTION
**Pull request by Otterian**
This PR aims to expand upon the DT Helm Chart to allow for two deployments due to the significant changes introduced in DT 4.0 and the future deprecation of the bundle image.
Also aims to address https://github.com/evryfs/helm-charts/issues/42
(https://docs.dependencytrack.org/changelog/)

I've not included a configmap for the frontend yet, as you can get away with passing the lines that goes in config.json as environment variables. I'm leaning towards having a configmap there aswell, though - just to keep it consistent across both deployments.

Heavy WIP. Feedback and suggestions welcome.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Please bump the version in the Chart.yaml to 1.0.0

**Comment by Otterian** [comment]
Due to the files in the frontend Docker image being owned by root, the container errs out with the current Security Context. https://github.com/DependencyTrack/frontend/pull/49 aims to change the permissions and the user it runs as.

**Comment by Otterian** [comment]
It's difficult to say what's going wrong here now, but at least the permission issue is fixed. More testing is needed.

**Comment by davidkarlsen** [comment]
Fixes #42.

**Pull request merged**
