### PR TITLE
Use common.ingress.backend on ingress.yaml

### PR DESCRIPTION
**Pull request by torrescd**
Use common.ingress.backend on ingress.yaml

for #57

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@torrescd have you tested it?

**Review by davidkarlsen — CHANGES_REQUESTED** [review]
Please also bump the chart patchversion.

**Comment by torrescd** [comment]
> @torrescd have you tested it?

Yes!

**Review by davidkarlsen — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@torrescd Thanks a lot for your contribution!

**Comment by davidkarlsen** [comment]
@torrescd would you like to add healthcheck probes too?

**Comment by smercier74** [comment]
Thanks for the fix

**Pull request merged**
