### PR TITLE
Add support for inline config

### PR DESCRIPTION
**Pull request by ekarlso**

### CODE REVIEW

**Review by davidkarlsen — COMMENTED** [review]
Why is this needed? It doesn't really change anything?

**Comment by ekarlso** [comment]
Hmm, does not `.Files.Lines .Values.mcrouterCommandParams.configFile` actually require you to have the config file as a actual file in the helm chart ?

**Comment by davidkarlsen** [comment]
> Hmm, does not `.Files.Lines .Values.mcrouterCommandParams.configFile` actually require you to have the config file as a actual file in the helm chart ?

I don't see how that could ever have worked, so I think we can simply drop the old stuff for clarity, so that it is either:
* generated default
* a json-block form values like you added

**Review by davidkarlsen — APPROVED** [review]
lgtm, thanks

**Pull request merged**
