### PR TITLE
Fix runner-operator crds

### PR DESCRIPTION
**Pull request by vmozgovoy**
Fix:
`
Error: failed to install CRD crds/garo.tietoevry.com_githubactionrunners.yaml: CustomResourceDefinition.apiextensions.k8s.io "githubactionrunners.garo.tietoevry.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[podTemplateSpec].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[podTemplateSpec].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
`

### CODE REVIEW

**Comment by vmozgovoy** [comment]
Hi, what's wrong with DCO check? I have added "Signed-off-by:" into the commit message.

**Comment by abhinavkhanna-sf** [comment]
@vmozgovoy Expected "Vladislav Mozgovoy vmozgovoy@mindk.com", but got "Vladyslav Mozghovyi vmozgovoy@mindk.com".
expected value does not have 'i' at the end

Waiting for the fix :)

**Comment by vmozgovoy** [comment]
@abhinavkhanna-sf Done. Thank you.

**Comment by abhinavkhanna-sf** [comment]
@vmozgovoy Thanks. Do you who will merge the PR and create the release?

**Comment by abhinavkhanna-sf** [comment]
@davidkarlsen Can you please look into this PR ?

**Comment by davidkarlsen** [comment]
Thanks - applied

**Pull request merged**
