### PR TITLE
Encapsulate service-account in if-blocks

### PR DESCRIPTION
**Pull request by Azulath**
In order to be able to disable `serviceaccount` completely I have encapsulated both if-block in their respective files accordingly.

### CODE REVIEW

**Review by davidkarlsen — APPROVED** [review]
lgtm - thanks!

**Comment by davidkarlsen** [comment]
@Azulath please bump the chart patch version too.

**Comment by Azulath** [comment]
> @Azulath please bump the chart patch version too.

I assume I have done this in [13881b8](https://github.com/evryfs/helm-charts/pull/202/commits/13881b80ea1942837170239f8a7332a7ae9145d1), there is no other patch version to bump, right? (hence the approve)

**Comment by davidkarlsen** [comment]
See https://github.com/evryfs/helm-charts/actions/runs/3339478142/jobs/5538161612#step:8:44

**Pull request merged**
