### PR TITLE
#164 updating dependency-tack version to 4.5.0

### PR DESCRIPTION
**Pull request by magnuskiro**
- updated dependency-track version to 4.5.0 / trying to resolve: https://github.com/evryfs/helm-charts/issues/164
- bumped chart version to 1.3.6
- ran helm-docs
- fixed link to issues in CONTRIBUTING.md

- ran the test.yml ci in personal fork with dummy version of other charts to pass linting. Dependency-track test seems to be ok. (https://github.com/magnuskiro/evryfs-helm-charts/actions/runs/2414702723)

### CODE REVIEW

**Comment by magnuskiro** [comment]
@davidkarlsen not sure if you get notified anywhere, so Hey :)

**Review by davidkarlsen — CHANGES_REQUESTED** [review]
Please only check in helm-docs  changes for this one chart.
Can you bump the chart version to 1.4.0 ?

**Comment by magnuskiro** [comment]
> 

Fixed

**Comment by davidkarlsen** [comment]
Fixes #164

**Review by davidkarlsen — APPROVED** [review]
lgtm

**Pull request merged**
