### PR TITLE
[Dependency Track] Pod annotations

### LINKED ISSUE #241: [dependency-track] Support podAnnotations
Currently there is no way to put annotations on pods.

**Is your feature request related to a problem? Please describe.**
We are trying to configure linkerd on all our pods and require annotations on pods to do so.

**Describe the solution you'd like**
The Bitnami chart for grafana-operator deployments has:
```
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.operator.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.operator.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.operator.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.operator.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
```
Given the use of the Bitnami common library by evryfs I think having the same would be good.

**Describe alternatives you've considered**
The only other way we've come up with is 'kubectl edit' :(

### PR DESCRIPTION
**Pull request by Yaytay**
Fixes #241

### CODE REVIEW

**Comment by vestigo-tech** [comment]
Hi @Yaytay ,

are there any chances this pull request might be merged any time soon?
I also need this feature.

Thanks.

**Comment by nkuzman** [comment]
Hi @Yaytay ,

is there a chance this pull request might be merged any time soon?
I also need this feature...

Thanks

**Comment by Yaytay** [comment]
I'm not using this helm chart any more and this repo is not mine so I don't whether it will ever be accepted.
Sorry that's not better news.

**Comment by nkuzman** [comment]
Thank you for your response, although I'm sorry to hear that :)
Hopefully someone else will be willing to take over...

**Pull request closed without merging**
